a=int(input("Enter a value:-"))
b=int(input("Enter a value:-"))
print(a+b)
a=float(input("Enter a value:-"))
b=float(input("Enter a value:-"))
print(a+b)
a=eval(input("Enter a value:-"))
b=eval(input("Enter a value:-"))
print(a+b)
